title: Smart-realestate
description: Smart realestate is a full stack project which fetches and predicts house prices
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
